### ISSUE TITLE
pyglet >=1.5.24 *is* compatible with ffmpeg 5.*

### ISSUE THREAD

**Issue by DManowitz** [conda-forge/pyglet-feedstock#84]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Although issue #70 indicates that pyglet is not compatible with ffmpeg 5.x, this is not fully correct.  Only pyglet <1.5.24 is not compatible with ffmpeg 5.x.  pyglet >=1.5.24 *is* compatible with ffmpeg 5.x, as confirmed by this exchange [here](https://github.com/pyglet/pyglet/issues/759) (also see issues [#603](https://github.com/pyglet/pyglet/issues/603) and [#541](https://github.com/pyglet/pyglet/issues/541) in pyglet's repo).

Thus, please remove the ffmpeg v4 dependency for pyglet versions >=1.5.24 (either make it depend only on ffmpeg or add ffmpeg v5 to these versions).

### Installed packages

```shell
N/A
```

### Environment info

```shell
N/A
```

**Comment by hoechenberger** [comment]
Thanks for letting us know! I will look into this later today

**Comment by DManowitz** [comment]
I see that there are new builds of pyglet 1.5.27 with updated dependencies.  However, the new dependency doesn't actually allow for any ffmpeg 5.x to be used with it because adding <=5 would only allow version 5.0.0 to be used, and there is no such version of ffmpeg available (only 5.0.1 and higher).  You need to change the upper limit of the dependency to be <6.

**Comment by hoechenberger** [comment]
Thanks for letting me know, my bad. Fix is coming.
